#156958165: Sort and Filtering search result
andela/nazgul-rc pull request #19
Opened 2018-05-24 11:45 UTC by omokolataiwo

#### What does this PR do?
Filters and sorts product search result.

#### Description of Task to be completed?
- Filter search result based on vendors and price
- Sort search and filtered result based on newest product, vendor, and price

#### How should this be manually tested?
- Clone the repository
- In the terminal run ```cd nazgul-rc```
- Run ```reaction``` in the terminal
- Open the browser and navigate to http://localhost:3000/
- Search for a product
- You can filter and sort from the search modal

#### What are the relevant pivotal tracker stories?
[Finishes: #156958165]

2018-05-24 12:36 UTC, andela-morekoya commented on e2eTest/sortFilter.test.js
> +  // "User should be able to sort search result by product price": browser => {
Why are these commented out?

2018-05-24 12:38 UTC, andela-morekoya commented
Are you using the same font styling as the rest of the app? It looks a bit different.

2018-05-28 09:29 UTC, omokolataiwo commented on e2eTest/sortFilter.test.js
> +  // "User should be able to sort search result by product price": browser => {
I created this pull request to create a review app and get feedback from the product owner. The test was not completed at this point.

2018-05-30 11:52 UTC, morekoya requested changes

2018-05-30 11:52 UTC, andela-morekoya commented on imports/plugins/included/ui-search/client/templates/searchModal/searchFilter.html
> +
Why do you have blank lines in-between?

2018-05-30 11:52 UTC, andela-morekoya commented on imports/plugins/included/ui-search/lib/components/searchModal.js
> +          {this.props.products.length > 0 && <ProductGridContainer products={this.props.products} unmountMe={this.props.unmountMe} isSearch={true} />}
Isn't this line longer that it should be? How come it wasn't flagged, has hound been turned off?

2018-05-31 09:57 UTC, morekoya approved these changes

2018-05-31 09:59 UTC, merged